// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    hello_world: {
        name: "hello_world";
        parameters: {
          /** STRING - use sql.string() */
          message: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          value: string;
        }>;
      };
  }
}
